# permissions for end users to view medusabackupschedules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: medusabackupschedule-viewer-role
rules:
- apiGroups:
  - medusa.k8ssandra.io
  resources:
  - medusabackupschedules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - medusa.k8ssandra.io
  resources:
  - medusabackupschedules/status
  verbs:
  - get
